home:
  path: /
  controller: App\Controller\HomeController::index

search_post:
  path: /search
  controller: App\Controller\HomeController::search

contact_mail:
  path: /mail
  controller: App\Controller\HomeController::sendMail

dashboard_user:
  path: /dashboard/user
  controller: App\Controller\DashboardController::manageUser

dashboard_post:
  path: /dashboard/post
  controller: App\Controller\DashboardController::managePost

dashboard_comment:
  path: /dashboard/comment
  controller: App\Controller\DashboardController::manageComment

dashboard_tags:
  path: /dashboard/tags
  controller: App\Controller\DashboardController::manageTags

dashboard_category:
  path: /dashboard/category
  controller: App\Controller\DashboardController::manageCategory

create_user:
  path: /user/create
  controller: App\Controller\UserController::create

login_user:
  path: /user/login
  controller: App\Controller\UserController::login

logout_user:
  path: /user/logout
  controller: App\Controller\UserController::logout

reset_password_user:
  path: /user/reset
  controller: App\Controller\UserController::resetPassword

delete_user:
  path: /user/delete/{slug}
  controller: App\Controller\UserController::delete

admin_user:
  path: /user/admin
  controller: App\Controller\UserController::admin

create_post:
  path: /post/create
  controller: App\Controller\PostController::create

update_post:
  path: /post/update/{slug}
  controller: App\Controller\PostController::update

delete_post:
  path: /post/delete/{slug}
  controller: App\Controller\PostController::delete

archiving_post:
  path: /post/archiving/{slug}
  controller: App\Controller\PostController::archiving

like_post:
  path: /post/like/{slug}
  controller: App\Controller\PostController::liked

pin_post:
  path: /post/pin/{slug}
  controller: App\Controller\PostController::pin

show_pined_posts:
  path: /post/pinned
  controller: App\Controller\PostController::showByPin

show_post:
  path: /post/{slug}
  controller: App\Controller\PostController::show

show_post_by_category:
  path: /post/category/{slug}
  controller: App\Controller\PostController::showByCategory

show_comments:
  path: /comments
  controller: App\Controller\CommentController::show

create_comment:
  path: /comment/create
  controller: App\Controller\CommentController::create

update_comment:
  path: /comment/update/{slug}
  controller: App\Controller\CommentController::update

delete_comment:
  path: /comment/delete/{slug}
  controller: App\Controller\CommentController::delete

report_comment:
  path: /comment/report/{slug}
  controller: App\Controller\CommentController::report

create_category:
  path: /category/create
  controller: App\Controller\CategoryController::create

delete_category:
  path: /category/delete/{slug}
  controller: App\Controller\CategoryController::delete

create_tags:
  path: /tags/create
  controller: App\Controller\TagsController::create

delete_tags:
  path: /tags/delete/{slug}
  controller: App\Controller\TagsController::delete